#!/bin/bash

INDIR=cases
OUTDIR=temp_out
MJAVAC=../mjavac.jar

function check {
    if [[ $1 != $TESTCASE_PAT ]]; then
        return
    fi

    INFILE=$INDIR/$1.xml
    OUTFILE=$OUTDIR/$1.res
    
    java -jar $MJAVAC unmarshal semantic $INFILE $OUTFILE

    echo -n "$1: "

    if [ "$(< $OUTFILE)" = $(printf "$2\n") ]; then
        printf "\x1b[0;32mSuccess\x1b[0m\n"
    else
        printf "\x1b[0;31mFailed\x1b[0m (expected $2)\n"
    fi
}

function check_valid {
    check $1 OK
}

function check_invalid {
    check $1 ERROR
}

function check_variants {
    check_valid "$1_valid"
    check_invalid "$1_invalid"
}

if [[ $# -eq 0 ]]; then
    TESTCASE_PAT="*"
else
    TESTCASE_PAT="$1"
fi

mkdir -p $OUTDIR

check_invalid declck_class_duplicate
check_invalid declck_class_duplicate_main
check_invalid declck_class_super_undecl
check_invalid declck_class_super_after
check_invalid declck_class_super_cycle
check_invalid declck_class_super_self
check_invalid declck_class_super_main

check_invalid declck_field_redecl
check_invalid declck_field_shadow
check_valid declck_field_unrelated

check_invalid declck_var_param_redecl
check_invalid declck_var_local_redecl
check_invalid declck_var_local_param
check_valid declck_var_unrelated

check_valid declck_local_field_shadow
check_valid declck_param_field_shadow

check_invalid declck_method_redecl
check_valid declck_method_override
check_valid declck_method_unrelated

check_invalid bindck_var_undecl_assign
check_invalid bindck_var_undecl_assign_arr
check_invalid bindck_var_undecl_sysout
check_invalid bindck_var_undecl_ret
check_invalid bindck_var_undecl_add
check_invalid bindck_var_undecl_arr_access
check_invalid bindck_var_undecl_arr_index
check_invalid bindck_var_undecl_owner_expr

check_invalid bindck_var_undecl_assign_main
check_invalid bindck_var_undecl_sysout_main

check_invalid bindck_type_undecl_local
check_valid bindck_type_before_local
check_valid bindck_type_after_local

check_invalid bindck_type_undecl_param
check_valid bindck_type_before_param
check_valid bindck_type_after_param

check_invalid bindck_type_undecl_field
check_valid bindck_type_before_field
check_valid bindck_type_after_field

check_invalid bindck_type_undecl_ret
check_invalid bindck_type_undecl_new
check_invalid bindck_type_undecl_ret_new

check_invalid typeck_sysout
check_invalid typeck_block
check_invalid typeck_if
check_invalid typeck_while
check_invalid typeck_assign_arr_arr
check_invalid typeck_assign_arr_idx
check_invalid typeck_assign_arr_val
check_invalid typeck_and
check_invalid typeck_not
check_invalid typeck_lt
check_invalid typeck_add
check_invalid typeck_sub
check_invalid typeck_mul
check_invalid typeck_arr_access_arr
check_invalid typeck_arr_access_idx
check_invalid typeck_arr_length
check_invalid typeck_new_arr
check_invalid typeck_arg
check_valid typeck_compound
check_invalid typeck_this_main

check_invalid typeck_assign
check_valid typeck_assign_ref
check_invalid typeck_assign_ref_unrelated
check_valid typeck_assign_ref_subtyping
check_invalid typeck_assign_ref_super
check_invalid typeck_assign_rv
check_valid typeck_assign_local_field_shadow

check_valid typeck_owner_expr_new
check_valid typeck_owner_expr_this
check_valid typeck_owner_expr_var
check_invalid typeck_owner_expr_lit
check_invalid typeck_owner_expr_bad_var

check_invalid typeck_call_method_undecl
check_valid typeck_call_method_inherited
check_invalid typeck_call_arity
check_invalid typeck_call_args
check_valid typeck_call_args_ref_subtyping
check_invalid typeck_call_args_ref_unrelated
check_invalid typeck_call_ret

check_invalid typeck_method_ret
check_invalid typeck_method_ret_ref
check_invalid typeck_method_ret_ref_super
check_valid typeck_method_ret_ref_subtyping

check_valid typeck_method_override
check_invalid typeck_method_override_arity
check_invalid typeck_method_override_args
check_valid typeck_method_override_args_ref
check_invalid typeck_method_override_args_ref_unrelated
check_invalid typeck_method_override_args_ref_subtyping
check_invalid typeck_method_override_args_ref_super
check_invalid typeck_method_override_ret
check_valid typeck_method_override_ret_ref
check_invalid typeck_method_override_ret_ref_unrelated
check_valid typeck_method_override_ret_ref_covariant
check_invalid typeck_method_override_ret_ref_contravariant
check_valid typeck_method_override_ret_ref_covariant_chain
check_invalid typeck_method_override_ret_ref_covariant_contravariant_chain

check_invalid initck_sysout
check_valid initck_sysout_assigned

check_invalid initck_field_shadowed
check_valid initck_field_shadowed_assigned

check_invalid initck_block
check_valid initck_block_assigned

check_invalid initck_if_cond
check_valid initck_if_cond_assigned

check_invalid initck_while_cond
check_valid initck_while_cond_assigned

check_invalid initck_assign_rv
check_valid initck_assign_rv_assigned

check_invalid initck_assign_self
check_valid initck_assign_self_assigned

check_invalid initck_assign_arr_arr
check_valid initck_assign_arr_arr_assigned

check_invalid initck_assign_arr_idx
check_valid initck_assign_arr_idx_assigned

check_invalid initck_assign_arr_rv
check_valid initck_assign_arr_rv_assigned

check_invalid initck_and
check_valid initck_and_assigned

check_invalid initck_not
check_valid initck_not_assigned

check_invalid initck_lt
check_valid initck_lt_assigned

check_invalid initck_add
check_valid initck_add_assigned

check_invalid initck_sub
check_valid initck_sub_assigned

check_invalid initck_mul
check_valid initck_mul_assigned

check_invalid initck_arr_access_arr
check_valid initck_arr_access_arr_assigned

check_invalid initck_arr_access_idx
check_valid initck_arr_access_idx_assigned

check_invalid initck_arr_length
check_valid initck_arr_length_assigned

check_invalid initck_call_owner
check_valid initck_call_owner_assigned

check_invalid initck_call_arg
check_valid initck_call_arg_assigned

check_invalid initck_ret
check_valid initck_ret_assigned

check_valid initck_field
check_valid initck_param

check_invalid initck_if
check_valid initck_if_assigned
check_invalid initck_if_thencase_assigned
check_valid initck_if_thencase_assigned_elsecase_nop
check_invalid initck_if_elsecase_assigned
check_valid initck_if_thencase_nop_elsecase_assigned
check_invalid initck_if_after_nop
check_valid initck_if_after_nop_assigned
check_invalid initck_if_after_thencase_assign_elsecase_nop
check_invalid initck_if_after_thencase_nop_elsecase_assign
check_valid initck_if_after_assign
check_valid initck_if_disjoint_vars
check_invalid initck_if_after_disjoint_vars
check_invalid initck_if_after_uncovered_vars
check_valid initck_if_after_contained_vars
check_valid initck_if_after_nested_uncovered_vars
check_valid initck_if_after_nested_contained_vars

check_invalid initck_while
check_valid initck_while_assigned
check_valid initck_while_body_assigned
check_invalid initck_while_after_nop
check_valid initck_while_after_nop_assigned
check_invalid initck_while_after_body_assign

check_variants provided_assignment
check_variants provided_int_var
check_variants provided_owner_expr

check_valid misc_method_and_variable_with_same_name
check_invalid misc_method_and_variable_with_same_name_uninit
check_invalid misc_method_and_variable_with_same_name_added_extends

check_valid misc_and_short_circuit_arr
check_invalid misc_and_short_circuit_arr_wrong_type

check_valid misc_array_access_in_access
check_invalid misc_array_access_in_access_missing_access

check_valid misc_array_iota_simple
check_invalid misc_array_iota_simple_index_uninit

check_valid misc_array_iota_print_all
check_invalid misc_array_iota_print_all_misspelled_method

check_valid misc_binary_search
check_invalid misc_binary_search_search_div_owner

check_valid misc_binary_tree
check_valid misc_binary_tree_compare_ntb_unassigned
check_invalid misc_binary_tree_compare_ntb_uninit

check_valid misc_bubble_sort
check_invalid misc_bubble_sort_print_missing_subscript

check_valid misc_factorial
check_valid misc_linear_search

check_valid misc_linked_list
check_invalid misc_linked_list_insert_swapped_args

check_valid misc_quick_sort
check_valid misc_subclass_fields

check_valid misc_subclass_field_access
check_invalid misc_subclass_field_access_misspelled_field

check_valid misc_partial_overrides
check_invalid misc_partial_overrides_a_unassigned

check_valid misc_tree_visitor
check_invalid misc_tree_visitor_missing_extends
