
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 10;
  public static final int LPAREN = 12;
  public static final int INT = 26;
  public static final int MINUS = 9;
  public static final int STATIC = 6;
  public static final int RPAREN = 13;
  public static final int L_CUR_PAREN = 14;
  public static final int NOT = 24;
  public static final int AND = 25;
  public static final int LT = 11;
  public static final int COMMA = 20;
  public static final int CLASS = 3;
  public static final int PLUS = 8;
  public static final int END_SENT = 21;
  public static final int ASSIGN = 22;
  public static final int MAIN = 4;
  public static final int IF = 31;
  public static final int L_ARRAY = 29;
  public static final int THIS = 36;
  public static final int DOT = 23;
  public static final int ID = 17;
  public static final int R_ARRAY = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int RETURN = 35;
  public static final int TRUE = 19;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int NUMBER = 16;
  public static final int VOID = 7;
  public static final int ELSE = 32;
  public static final int WHILE = 33;
  public static final int PUBLIC = 2;
  public static final int EXTENDS = 5;
  public static final int STRING = 38;
  public static final int FALSE = 18;
  public static final int R_CUR_PAREN = 15;
  public static final int PRINT = 37;
  public static final int LENGTH = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "MAIN",
  "EXTENDS",
  "STATIC",
  "VOID",
  "PLUS",
  "MINUS",
  "MULT",
  "LT",
  "LPAREN",
  "RPAREN",
  "L_CUR_PAREN",
  "R_CUR_PAREN",
  "NUMBER",
  "ID",
  "FALSE",
  "TRUE",
  "COMMA",
  "END_SENT",
  "ASSIGN",
  "DOT",
  "NOT",
  "AND",
  "INT",
  "BOOLEAN",
  "NEW",
  "L_ARRAY",
  "R_ARRAY",
  "IF",
  "ELSE",
  "WHILE",
  "LENGTH",
  "RETURN",
  "THIS",
  "PRINT",
  "STRING"
  };
}

